### ISSUE TITLE
You aren't doing something correctly 

### ISSUE THREAD

**Issue by jakeajames** [nathanaccidentally/OSRestore#21]
`echo "Removing /var/mobile and it's contents…"`

`rm -R Backups`

`rm -R Containers`

`rm -R Documents`

`rm -R Downloads`

`rm -R Media`

`rm -R MobileSoftwareUpdate`

`echo "Removed all contents except for Library from /var/mobile`

I store other stuff in /var/mobile. This isn't going to work. You should **really** remove **everything** except Library. Make some kind of check and if the folder = Library and in this case don't remove it. :)

**Comment by ThatNerdyPikachu** [comment]
I see.... we will fix this, sorry about that!

**Comment by nathanaccidentally** [comment]
I mean, this is technically possible. But you see those posts about apps being removed? If that were to happen to /var/mobile/Library that would be **very bad.**
