### ISSUE TITLE
Hey, ummm, why did u install MTerminal?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [nathanaccidentally/OSRestore#8]
Why does the process need it?

**Comment by ipadkid358** [comment]
It was recommended by the tutorial that this script is based from

https://www.reddit.com/r/jailbreak/comments/60ehf0/tutorial_an_actual_dyi_solution_to_semirestore/?st=J0IWNZFF&sh=3b5c0e47

**Comment by nathanaccidentally** [comment]
It initiates Coolstars stashing for the first time if it hasn't been initiated yet. It get's removed when done with the script.
